title: Abijith Pandath
logo: assets/Headshot1.png
# description below the image
show downloads: true
author:
  email: abijithabi3416@gmail.com
  linkedin: www.linkedin.com/in/abijithpandath
theme: jekyll-theme-minimal
